{% set name = "ldas-tools-frameAPI" %}
{% set version = "3.0.3" %}

# upstream dependency versions
{% set ldas_tools_cmake_version = "1.3.0" %}
{% set ldas_tools_al_version = "2.6.7" %}
{% set ldas_tools_framecpp_version = "2.8.1" %}
{% set ldas_tools_filters_version = "2.6.6" %}
{% set ldas_tools_ldasgen_version = "2.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: b1ead237903a3a46632328bee59891e9f0d98ceccae169889f42bf009882729b

build:
  error_overdepending: true
  error_overlinking: true
  number: 3
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("ldas-tools-frameapi", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake >=3.6
    - make  # [unix]
    - pkg-config  # [unix]
  host:
    - ldas-tools-al >={{ ldas_tools_al_version }}
    - ldas-tools-cmake >={{ ldas_tools_cmake_version }}
    - ldas-tools-filters >={{ ldas_tools_filters_version }}
    - ldas-tools-framecpp
    - ldas-tools-framecpp >={{ ldas_tools_framecpp_version }}
    - ldas-tools-ldasgen >={{ ldas_tools_ldasgen_version }}
    - libboost-devel

test:
  requires:
    - pkg-config  # [unix]
  commands:
    # generate fake data
    - framecpp_sample
    # generate analysis-ready segments
    - ldas_analysis_ready --frame-file-pattern "*.gwf" --ifo Z0 --analysis-ready-channel RAMPED_INT_8U_1
    # sanity check headers and pkg-config
    - test -d ${PREFIX}/include/frameAPI  # [unix]
    - pkg-config --print-errors --exact-version {{ version }} ldastools-ldasframe  # [unix]

about:
  home: https://wiki.ligo.org/Computing/LDASTools
  dev_url: https://git.ligo.org/ldastools/LDAS_Tools
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: LDAS tools frameAPI library
  description: This provides the runtime libraries for the frameAPI library.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
