{% set name = "ldas-tools-frameAPI" %}
{% set version = "2.6.7" %}

# upstream dependency versions
{% set ldas_tools_cmake_version = "1.2.3" %}
{% set ldas_tools_al_version = "2.6.7" %}
{% set ldas_tools_framecpp_version = "3.0.2" %}
{% set ldas_tools_filters_version = "2.6.6" %}
{% set ldas_tools_ldasgen_version = "2.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: 53dd46019f44459dc5cd05cbde80b6f33e5989f7790f31609acc3bd377d35c5c

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("ldas-tools-frameapi", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.6
    - make  # [unix]
    - pkg-config  # [unix]
  host:
    - ldas-tools-al >={{ ldas_tools_al_version }}
    - ldas-tools-cmake >={{ ldas_tools_cmake_version }}
    - ldas-tools-filters >={{ ldas_tools_filters_version }}
    - ldas-tools-framecpp >={{ ldas_tools_framecpp_version }}
    - ldas-tools-ldasgen >={{ ldas_tools_ldasgen_version }}
  run:
    - ldas-tools-al >={{ ldas_tools_al_version }}
    - ldas-tools-framecpp >={{ ldas_tools_framecpp_version }}
    - ldas-tools-filters >={{ ldas_tools_filters_version }}
    - ldas-tools-ldasgen >={{ ldas_tools_ldasgen_version }}

test:
  requires:
    - pkg-config  # [unix]
  commands:
    - test -d ${PREFIX}/include/frameAPI  # [unix]
    - test -f ${PREFIX}/lib/libldasframe${SHLIB_EXT}  # [unix]
    - pkg-config --print-errors --exact-version {{ version }} ldastools-ldasframe  # [unix]

about:
  home: https://wiki.ligo.org/Computing/LDASTools
  dev_url: https://git.ligo.org/ldastools/LDAS_Tools
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: LDAS tools frameAPI library
  description: This provides the runtime libraries for the frameAPI library.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - emaros
