appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: c/NrVrzRht02Njm4L58kWDMmW/XfnqixWR1pidGQ3KhmOd7yFqdGIusFZv3iP167o6bBgJZYL4hH8vUaGFOx/uTyZ41bgNTA6espDo4ulXG/ygmfGI2A/LYpzMvnaPh/aq/HZAbIBxg/PpvExHCl/BJ4N63X0e152qn3bpOy+TGmKB0NRBMR0uu51G0g7OUVFkAEH/gu3/L875k2WNuBBA974R9Mdd1sZ8tRNgtva7AJICaV/0YL1Uu1P247o+NGvDFzfOj0mEQhExJMSQxVPLVpcRI8WRq90/sOo9ppRXyodg7Y1rgL6R5x4gQy4w+RCbfDxNOs8vcQNPQeustjGRdzHn6YyS8ubAMD4zkKoSXkYP065DM/InJOaQfOqFe8qqvktcsRscJTXLpctZDTk/Doag8Dx1O4e1bhx+Iqq+cfqAZ+mxkFI9pu+fbGk2HL+LE/S693P+BGqIIN/O8cfK8tSRjtZH+cmH2MA1pgxRfXwfCjCy3w25WyqGTDijOQ/7UXMnaePbn+eCKaTcagu1dgGfGKXGY1bOhd+Mvpfdxq570zj89F9BdzGfPJ07Y4tDIMx9BMv5WwIWoDczAnaAeAXy485W/+3AOBDK+SuZG4MypathWF+JG0Bl3JLK3n5xeHkJ35YaxW0FzsI9P3QgFdn839YVvV60vyTDgpD0A=}
