appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: QTn1u6H0/xo0yRBbtVpUjKnOwP80fVbRhgVp4LPxzVscs54yxr1mYizQ0jHOUX+TS/BzlAXlkoAe3jz3mdCFquxf4ERpCBM/9o/qZCHK0uxPqelVoAeJyqjtcdMhOIzqD+AX1a2Pf9sxFrPsuY/c5vtdTn1mG2B1iWCiLYhI5am1LPavYQPfUnGM3T2iuJhDyr1wkLUph7Az1owVRXaPLxRCgFTKXA68h3NF+k31K2WgSp/6ZFYD8NZ2yIBynvkovQY1H32tnUDke9HOIaa83dvzDPS5Xuxzyl3kACjGSoTbzvhpGLdPPM9YvPHaMlOD9M+m0W1P2TRpsq+komlLtPybLPIBqOTkONP9z+tTAbFmauBxO9MA3hfBn+MgwE3yUenDNCYavCwJxCc60zs2QunLCYeLkcvxWQC7yLQ2ZjNN5dJMvyu57ZopP+kgKfTkBBVEbvyxZQSfMzy0mgtDvf1Cq67cfVD+sQFhJhcTI/tuyNY4YExsD3XCIlgQ8V0Ouldfkasw4H55SE4x22ksdwwUHEabxERk71J3SKGhI6CpxwukK8ih4oZpWsCoz//L32705A6UNI3Ol8SMqexHAZ+NWAF7yC07mpJ00CGuL/S1fIALl9ohItFTBfHJLiAV35sDvcA6G2bL0w0Somj93c84E+StxPw4edhlcZ4zgnk=}
